let books=[
    {
        'Ad':'PocketBook 614 White',
        'Displeyin tipi':'E link, Pearl, boz : 16',
        'Ekran ölçüsü':'800x600',
        'Ekranın ölçüsü , düyümlə':6,
        'Qəbul etdiyi mətn faylları':'PDF, PDF (DRM), EPUB, EPUB (DRM) , DJVU, FB 2, ZİP, DOC, DOCX,',
        'Qəbul etdiyi qrafik format':'JPEG, BMP, PNG, TIFF',
        'Prosessor':'1 Ghs',
        'Operativ yaddaş, Mb':256,
        'Daxili yaddaş, Мб':4096,
        'Əlavə yaddaş':'Micro USB',
        'Max, əlavə yaddaş imkanı, Мб':'до 32 ГБ',
        'Ölçü, mm':'174,4 х 114,6 х 8,3',
        'Çəki, q':'188',
        'Əlavə':'Albom, kalendar, kalkulyator, şahmat, snake,  sudoku',
        'Korpusun materialı':'Plastik',
        'img':'img/1390809469-elektronnaya_kniga_6_pocketbook_614_white_1.jpg'
    },
    {
        'Ad':'POCKETBOOK 614 BASIC 3 BLACK',
        'Ekranın tipi':'E Ink Pearl',
        'Ekranın ölçüsü , düyümlə':6,
        'Akkmlyatorun tipi':'Li-ion',
        'Akkumlyatorun həcmu ,mah':1300,
        'Prosessorun tezliyi , MGh':1000,
        'Operativ yaddaş ,MB':'256MB',
        'Daxili yaddaş ,MB':'8GB',
        'Əlavə yaddaş':'microSD (TransFlash)',
        img:'img/1569929583-pocketbook_614_basic_3_black_images_8659144919.jpg'
    },
    {
        'Ad':'POCKETBOOK 616',
        'Ekranın tipi':'E-Ink Carta',
        'Ekranın ölçüsü':'1024x758',
        'Ekranın ölçüsü , düyümlə':6,
        'İşıqlandırma':'+',
        'Akkumlyatorun həcmu ,mah':'1300',
        'Prosessorun tezliyi , MGh':1000,
        'Operativ yaddaş ,MB':'256MB',
        'Daxili yaddaş ,MB':'8GB',
        'Əlavə yaddaş	':'microSD (TransFlash)',
        'Ölçü , mm':'108x161x8',
        'Çəki , q	':'155',
        img:'https://www.salonsvyazi.ru/images/ebooks2/full/1569934253-orig'
    },
    {
        'Ad':'POCKETBOOK 616 BLACK',
        'Ekranın tipi':'E-Ink Carta',
        'Ekranın ölçüsü':'1024x758',
        'Ekranın ölçüsü , düyümlə':6,
        'İşıqlandırma':'+',
        'Akkumlyatorun həcmu ,mah':'1300',
        'Prosessorun tezliyi , MGh':1000,
        'Operativ yaddaş ,MB':'256MB',
        'Daxili yaddaş ,MB':'8GB',
        'Əlavə yaddaş	':'microSD (TransFlash)',
        'Ölçü , mm':'108x161x8',
        'Çəki , q	':'155',
        img:'https://www.salonsvyazi.ru/images/ebooks2/full/1569934246-orig'

    },
    {
        'Ad':'BOOX CAESAR 3 BLACK + MICROSD 16GB',
        'Ekranın tipi':'E Ink Carta',
        'Ekranın ölçüsü	':'758x1024',
        'İşıqlandırma':'MOON Light+ c цветовой регулировкой температуры',
        'Akkumlyatorun həcmu ,mah':'3000',
        'Əməliyyat sistemi':'Android 4.4',
        'Nüvələrin sayı':4,
        'Prosessorun tezliyi , MGh':'1200',
        'Operativ yaddaş ,MB':'512',
        'Daxili yaddaş ,MB':'8ГБ',
        'Əlavə yaddaş':'microSD (TransFlash)',
        'Ölçü , mm':'170×117×8,7',
        'Çəki , q':182,
        img:'img/1543484395-_onyx_Caesar3_black_front_1000x1000-500x500.jpg',
    },
    {
        'Ad':'POCKETBOOK 641 AQUA',
        'Ekranın tipi':'E-Ink Carta',
        'Ekranın ölçüsü':'1024x758',
        'Ekranın ölçüsü , düyümlə':6,
        'Sensorlu ekran':'+',
        'İşıqlandırma':'+',
        'Akkumlyatorun həcmu ,mah':'1500',
        'Prosessorun tezliyi , MGh':1000,
        'Operativ yaddaş ,MB	':'256MB',
        'Daxili yaddaş ,MB':'8GB',
        'Wi-Fi':'+',
        'Ölçü , mm':'115x174x9',
        'Çəki , q':180,
        img:'https://www.salonsvyazi.ru/images/ebooks2/full/1569931099-orig'
    },
    {
        Ad:'BOOX VASCO DA GAMA 3 BLACK + MICROSD 16GB',
        'Ekranın tipi':'E Ink Carta',
        'Ekranın ölçüsü':'758x1024',
        'Ekranın ölçüsü , düyümlə':'6',
        'Sensorlu ekran':'+',
        'İşıqlandırma':'MOON Light+ c цветовой регулировкой температуры',
        'Əməliyyat sistemi':'Android 4.4',
        'Nüvələrin sayı	':'4',
        'Prosessorun tezliyi , MGh':1200,
        'Operativ yaddaş ,MB	':512,
        'Daxili yaddaş ,MB':'8GB',
        'Əlavə yaddaş':'microSD (TransFlash)',
        'Wi-Fi':'+',
        'Ölçü , mm':'170×117×8,7',
        'Çəki , q':182,
        img:'img/1543484140-onyx_vasco3_black_front_1000x1000-500x500.jpg',
    },
    {
        'Ad':'POCKETBOOK 627 BLACK',
        'Ekranın tipi':'E-Ink Carta',
        'Ekranın ölçüsü	':'1024x758',
        'Ekranın ölçüsü , düyümlə':6,
        'Sensorlu ekran':'+',
        'İşıqlandırma':"+",
        'Prosessorun tezliyi , MGh':1000,
        'Operativ yaddaş ,MB':'512МБ',
        'Daxili yaddaş ,MB':'8 ГБ',
        'Əlavə yaddaş':'microSD (TransFlash)',
        'Wi-Fi':'+',
        'Ölçü , mm':'108x161x8',
        'Çəki , q':155,
        img:'https://www.salonsvyazi.ru/images/ebooks2/full/1569933234-orig'
    },
    {
        'Ad':'POCKETBOOK 627 СЕРЕБРО',
        "Ekranın tipi":'E-Ink Carta',
        'Ekranın ölçüsü	':'1024x758',
        'Ekranın ölçüsü , düyümlə':6,
        'Sensorlu ekran':'+',
        'İşıqlandırma':'+',
        'Prosessorun tezliyi , MGh':1000,
        'Operativ yaddaş ,MB	':'512МБ',
        'Daxili yaddaş ,MB':'8 ГБ',
        'Əlavə yaddaş':'microSD (TransFlash)',
        'Wi-Fi':'+',
        'Ölçü , mm':'108x161x8',
        'Çəki , q':155,
        img:'https://www.salonsvyazi.ru/images/ebooks2/full/1569933212-orig'
    },
    {
        "Ad":'POCKETBOOK 627 ИЗУМРУДНЫЙ',
        'Ekranın tipi':'E-Ink Carta',
        'Ekranın ölçüsü':'1024x758',
        'Ekranın ölçüsü , düyümlə':6,
        'Sensorlu ekran':'+',
        'İşıqlandırma':'+',
        'Prosessorun tezliyi , MGh':1000,
        'Operativ yaddaş ,MB':'512МБ',
        'Daxili yaddaş ,MB':'8 ГБ',
        'Əlavə yaddaş':'microSD (TransFlash)',
        'Wi-Fi':'+',
        'Ölçü , mm':'108x161x8',
        'Çəki , q':'155',
        img:'https://www.salonsvyazi.ru/images/ebooks2/full/1569933249-orig'
    },
    {
        'Ad':'BOOX DARWIN 5 GRAPHITE + MICROSD 16GB',
        'Ekranın tipi':'E Ink Carta',
        'Ekranın ölçüsü':'758x1024',
        'Ekranın ölçüsü , düyümlə':'6',
        'Sensorlu ekran':'+',
        'İşıqlandırma':'MOON Light+ с регулировкой цветовой температуры',
        'Nüvələrin sayı':4,
        'Prosessorun tezliyi , MGh':1200,
        'Operativ yaddaş ,MB':'1ГБ',
        'Daxili yaddaş ,MB':'8ГБ',
        'Əlavə yaddaş':'microSD (TransFlash)',
        'Wi-Fi':'+',
        'Ölçü , mm':'170×117×8,7',
        'Çəki , q':182,
        img:'img/1543483750-onyx_darwin5_grey_front_1000x1000-500x500.jpg'
    },
    {
        "Ad":'BOOX DARWIN 5 BLACK + MICROSD 16GB',
        'Ekranın tipi':'E Ink Carta',
        'Ekranın ölçüsü':'758x1024',
        'Ekranın ölçüsü , düyümlə':'6',
        'Sensorlu ekran':'+',
        'İşıqlandırma':'MOON Light+ с регулировкой цветовой температуры',
        'Nüvələrin sayı':'4',
        'Prosessorun tezliyi , MGh':'1200',
        'Operativ yaddaş ,MB':'1ГБ',
        'Daxili yaddaş ,MB':'8ГБ',
        'Əlavə yaddaş':'microSD (TransFlash)',
        'Wi-Fi':'+',
        'Ölçü , mm':'170×117×8,7',
        'Çəki , q':'182',
        img:'img/1543483768-onyx_darwin5_black_front_1000x1000-500x500.jpg'
    },
    {
        'Ad':'BOOX DARWIN 5 WHITE + MICROSD 16GB',
        'Ekranın tipi':'E Ink Carta',
        'Ekranın ölçüsü':'758x1024',
        'Ekranın ölçüsü , düyümlə':'6',
        'Sensorlu ekran':'+',
        'İşıqlandırma':'MOON Light+ с регулировкой цветовой температуры',
        'Nüvələrin sayı':'4',
        'Prosessorun tezliyi , MGh':'1200',
        'Operativ yaddaş ,MB':'1ГБ',
        'Daxili yaddaş ,MB':'8ГБ',
        'Əlavə yaddaş':'microSD (TransFlash)',
        'Wi-Fi':'+',
        'Ölçü , mm':'170×117×8,7',
        'Çəki , q':'182',
        img:'img/1559720060-5336.750x0.jpg',
    },
    {
        "Ad":'BOOX DARWIN 6 BLACK + MICROSD 16GB',
        "Ekranın tipi":'E Ink Carta Plus',
        'Ekranın ölçüsü':'1072×1448',
        'Ekranın ölçüsü , düyümlə':'6',
        'Sensorlu ekran':'+',
        'İşıqlandırma':'MOON Light',
        'Akkumlyatorun həcmu ,mah':'3000',
        'Əməliyyat sistemi':'Android',
        'Nüvələrin sayı':'4',
        'Prosessorun tezliyi , MGh':'1200',
        'Operativ yaddaş ,MB':'1ГБ',
        'Daxili yaddaş ,MB':'8ГБ',
        'Əlavə yaddaş':'microSD (TransFlash)',
        'Wi-Fi':'+',
        'Ölçü , mm':'170×117×8,7',
        'Çəki , q':'182',
        img:'img/1543483371-onyx_darwin6_black_front_1000x1000-500x500.jpg'
    },
    {
        "Ad":'BOOX MONTE CRISTO 4 BLACK + MICROSD 16GB',
        'Ekranın tipi':'E Ink Carta Plus',
        'Ekranın ölçüsü':'1072×1448',
        'Ekranın ölçüsü , düyümlə':'6',
        'Sensorlu ekran':'+',
        'İşıqlandırma':'MOON Light+',
        'Akkumlyatorun həcmu ,mah':'3000',
        'Əməliyyat sistemi':'Android',
        'Nüvələrin sayı':'4',
        'Prosessorun tezliyi , MGh':'1200',
        'Operativ yaddaş ,MB':'1024',
        'Daxili yaddaş ,MB':'8 ГБ',
        'Əlavə yaddaş':'microSD (TransFlash)',
        'Wi-Fi':'+',
        'Bluetooth':'+',
        'Ölçü , mm':'114x158,9x8',
        'Çəki , q':'205',
        img:'img/1553840989-Monte_Cristo4_1000x1000.jpg'
    },
    {
        "Ad":'BOOX EUCLID BLACK + MICROSD 32GB',
        img:'https://www.salonsvyazi.ru/images/ebooks2/full/1540144457-Euclid_pic_45_1000x1000.jpg'
    }
    ,{
        "Ad":'GULLIVER BLACK + MICROSD 32GB',
        'Ekranın tipi':'E Ink Mobius Carta',
        'Ekranın ölçüsü	':'1404 x 1872',
        'Ekranın ölçüsü , düyümlə':'10.3',
        'Akkumlyatorun həcmu ,mah':'4100',
        'Əməliyyat sistemi':'Android',
        'Nüvələrin sayı':'4',
        'Prosessorun tezliyi , MGh':'1600',
        'Operativ yaddaş ,MB':'2ГБ',
        'Daxili yaddaş ,MB':'32ГБ',
        'Wi-Fi':'+',
        'Ölçü , mm':'249,5×177,8×6,8',
        'Çəki , q':'325',
        img:'https://www.salonsvyazi.ru/images/ebooks2/full/1539248885-Gulliver_800x800_4-500x500.jpg',
    },
    {
        'Ad':'MAX 2 BLACK + MICROSD 32GB',
        'Ekranın tipi':'E Ink Carta',
        'Ekranın ölçüsü':'1650×2200',
        'Ekranın ölçüsü , düyümlə':'13.3',
        'Sensorlu ekran':'+',
        'Akkumlyatorun həcmu ,mah':'4100',
        'Əməliyyat sistemi':'Android',
        'Prosessorun tezliyi , MGh':'1600',
        'Operativ yaddaş ,MB':'2ГБ',
        'Daxili yaddaş ,MB':'32ГБ',
        'Wi-Fi':'+',
        'Ölçü , mm':'325×237×7,5',
        'Çəki , q':'550',
        img:'https://www.salonsvyazi.ru/images/ebooks2/full/1527419513-MAX_pic_1.jpg',
    }
]